Let the join listener use a cached result of CheckBuildFile
YHDiamond/GeyserUpdater pull request #45
Opened 2021-03-05 17:02 UTC by Konicai

Also, the join listener now actually calls CheckBuildFile. 

We record the time at which the check method was last called, and we cache the result of any direct checks. 
We pass a boolean forPlayer set to true to the check method to indicate we are accepting cached results. I'm not fond of this name, however I chose it over something like `allowedCached` because I a console log message isn't sent when a cached vale is used. Any input is appreciated. 

The time at which the method was last called is initially set to 0, which means a direct check always occurs first.
We use a direct check and refresh the cache if the cached result is older than 30 minutes. 

Only tested on Bungee,

2021-03-05 18:54 UTC, rtm516 requested changes

2021-03-05 18:54 UTC, rtm516 commented on src/main/java/com/alysaa/geyserupdater/bungee/BungeeUpdater.java
> +        getProxy().getScheduler().schedule(this, () -> CheckBuildFile.checkSpigotFile(true), 30, 720, TimeUnit.MINUTES);
Think this is a typo
```suggestion
        getProxy().getScheduler().schedule(this, () -> CheckBuildFile.checkBungeeFile(true), 30, 720, TimeUnit.MINUTES);
```

2021-03-05 20:10 UTC, Konicai commented
Oops, thank you

2021-03-07 17:27 UTC, Jens-Co approved these changes
Seems fine for me!

2021-03-07 17:27 UTC, merged